### ISSUE TITLE
Noah-MP Docker Container Setup (Windows): Regression Test Failed

### ISSUE THREAD

**Issue by leiapauline** [NCAR/hrldas#183]
Hello. I am following the tutorial to setup NoahMP using the Docker container on Windows. I was able to download the UFS/Noah-MP Component Model but there was an error during the test. Any guidance would be greatly appreciated.

Sincerely,
Leia Pauline

Please see below for the error received,
`UFS_tasks         : 6`
`FAILED TESTS:`
`001 datm_cdeps_lnd_era5_gnu failed in check_result`
`REGRESSION TEST FAILED`
`Elapsed time: 00h:03m:41s. Have a nice day!`
`rt.sh finished`,

and a snippet of the log_local file,
`baseline dir = /opt/RT/NEMSfv3gfs/develop-20231003/datm_cdeps_lnd_era5_gnu`
`working dir  = /opt/scratch/root/FV3_RT/rt_575/datm_cdeps_lnd_era5_gnu`
`Checking test 001 datm_cdeps_lnd_era5_gnu results ....`
` Comparing ufs.cpld.lnd.out.2011-01-01-43200.tile1.nc .........NOT OK`
` Comparing ufs.cpld.lnd.out.2011-01-01-43200.tile2.nc .........NOT OK`
` Comparing ufs.cpld.lnd.out.2011-01-01-43200.tile3.nc .........NOT OK`
` Comparing ufs.cpld.lnd.out.2011-01-01-43200.tile4.nc .........NOT OK`
` Comparing ufs.cpld.lnd.out.2011-01-01-43200.tile5.nc .........NOT OK`
` Comparing ufs.cpld.lnd.out.2011-01-01-43200.tile6.nc .........NOT OK`
`Test 001 datm_cdeps_lnd_era5_gnu FAIL`.

**Comment by cenlinhe** [comment]
@uturuncoglu could you please answer this queston?
