### ISSUE TITLE
Variable issue in HRLDAS_setup_********_d1

### ISSUE THREAD

**Issue by liu-13** [NCAR/hrldas#214]
Dear Professor:
Hello, I'm now trying to replace the initial data obtained by ERA5-land via create_forcing.exe with the data obtained by WRF, that is, the data in the file HRLDAS_setup_********_d1, but I'm not very clear about what the variables in it represent exactly. Can you please answer me?
![acee0c3c-0972-4b6f-ae75-4e84e0899330](https://github.com/user-attachments/assets/9ec9bf29-1584-4182-be27-0aee6e632a1d)

**Comment by tslin2** [comment]
Hi,
It looks alright to me, I also had these variables in my HRLDAS_setup file.

**Comment by liu-13** [comment]
> Hi, It looks alright to me, I also had these variables in my HRLDAS_setup file.

You may not have understood what I meant, I meant trying to figure out what the significance of these variables is. What do they mean?

**Comment by tslin2** [comment]
TMN is annual mean deep soil temperature [K]
HGT is topography height [m]
SEAICE is sea ice fraction [-] (should be 0.0 for a land point)
MAPFAC_MX is Mapfactor (x-dir) on mass grid
MAPFAC_MY is Mapfactor (y-dir) on mass grid
SHDMAX is maximum annual vegetation percentage [0-100]
SHDMIN is minimum annual vegetation percentage [0-100]
LAI is leaf area index [m2/m2] (initial state)
XLAND is land mask [-] (should be 1 for a land point)
IVGTYP is vegetation type 
ISLTYP is soil texture type
SNOW is snow water equivalent [mm] (initial state)
CANWAT is plant canopy surface water [mm] (initial state)
TSK is surface skin temperature [K] (initial state)
DZS is soil layer thicknesses [m] 
ZS is soil node depths [m] 
TSLB is layer soil temperature [K] (initial state)
SMOIS is layer volumetric soil moisture [m3/m3] (initial state)

**Comment by liu-13** [comment]
> TMN is annual mean deep soil temperature [K] HGT is topography height [m] SEAICE is sea ice fraction [-] (should be 0.0 for a land point) MAPFAC_MX is Mapfactor (x-dir) on mass grid MAPFAC_MY is Mapfactor (y-dir) on mass grid SHDMAX is maximum annual vegetation percentage [0-100] SHDMIN is minimum annual vegetation percentage [0-100] LAI is leaf area index [m2/m2] (initial state) XLAND is land mask [-] (should be 1 for a land point) IVGTYP is vegetation type ISLTYP is soil texture type SNOW is snow water equivalent [mm] (initial state) CANWAT is plant canopy surface water [mm] (initial state) TSK is surface skin temperature [K] (initial state) DZS is soil layer thicknesses [m] ZS is soil node depths [m] TSLB is layer soil temperature [K] (initial state) SMOIS is layer volumetric soil moisture [m3/m3] (initial state)

thank you

**Comment by cenlinhe** [comment]
@tslin2 Thank you for replying to this question. I would suggest we add a instruction/note file under the tutorial folder to list all these explanations for variables in HRLDAS_setup file. It could be a txt file or pdf file or .ipynb file. Could you please create a PR to the develop branch for this? Please let me know if you would like me to do it. Thanks!

**Comment by cenlinhe** [comment]
This issue has been fixed in this PR which has been merged to the develop branch: https://github.com/NCAR/hrldas/pull/215
