### ISSUE TITLE
PROBLEM:  Requested field name does not match the name in the Vtable entry. when 

### ISSUE THREAD

**Issue by JiangJinghong** [NCAR/hrldas#23]
I tried the workflow of GLDAS to  a small DOMAIN(the WPS-4.2 namelist domain key settings: dx = 1000; dy = 100, ref_lat = 35, ref_lon = 105, e_we = 200, e_sn = 200) from 2001010200-2001123100, the Variables I need are successfully extructed in folders as root/extracted/Tair   root/extracted/V   root/extracted/U   root/extracted/LWdown   root/extracted/SWdown   root/extracted/Wind   root/extracted/Snowf   root/extracted/Rainf   root/extracted/Psurf   root/extracted/Qair   root/extracted/INIT   root/extracted/Precip.   
But the last step to creat the forcing data(./create_forcing.exe namelist.input.GLDAS) called a problem:
`$ ./create_forcing.exe namelist.input.GLDAS
  11 |   1  |   0  |      | T2D      | K         | Temperature       at 2 m                |  0  |  0  |  0  | 103 |
  51 |   1  |   0  |      | Q2D      | kg/kg     | Specific Humidity at 2 m                |  0  |  1  |  0  | 103 |
  33 |   1  |   0  |      | U2D      | m/s       | U                 at 10 m               |  0  |  2  |  2  | 103 |
  34 |   1  |   0  |      | V2D      | m/s       | V                 at 10 m               |  0  |  2  |  3  | 103 |
   1 |   1  |   0  |      | PSFC     | Pa        | Surface Pressure                        |  0  |  3  |  0  |   1 |
  59 |   1  |   0  |      | RAINRATE | kg/m^2/s  | Precipitation Rate                      |  0  |  1  |  8  |   1 |
 204 |   1  |   0  |      | SWDOWN   | W/m^2     | Downward short-wave radiation flux      |  0  |  4  | 192 |   1 |
 205 |   1  |   0  |      | LWDOWN   | W/m^2     | Downward long-wave radiation flux       |  0  |  5  | 192 |   1 |
   7 |   1  |   0  |      | TERRAIN  | m         | Terrain field of source analysis        |  2  |  0  |  7  |   1 |
 138 |   1  |   0  |      | TSK      | K         | Skin temperature                        |  0  |  0  |  0  |   1 |
  65 |   1  |   0  |      | SNOW     | kg/m^2    | Water equivalent snow depth             |  0  |  1  | 13  |   1 |
  71 |   1  |   0  |      | CANWAT   | kg/m^2    | Plant Canopy Surface Water              |  2  |  0  | 196 |   1 |
  86 | 112  |   0  |   4  | SMOIS_1  | gldas     | Soil Moist 0-10 cm below grn layer (Up) |  2  |  0  | 192 | 106 |
  86 | 112  |   0  |   3  | SMOIS_2  | gldas     | Soil Moist 10-40 cm below grn layer     |  2  |  0  | 192 | 106 |
  86 | 112  |   0  |   2  | SMOIS_3  | gldas     | Soil Moist 40-100 cm below grn layer    |  2  |  0  | 192 | 106 |
  86 | 112  |   0  |   1  | SMOIS_4  | gldas     | Soil Moist 100-200 cm below gr layer    |  2  |  0  | 192 | 106 |
  85 | 112  |   0  |   4  | STEMP_1  | K         | T 0-10 cm below ground layer (Upper)    |  2  |  0  |  2  | 106 |
  85 | 112  |   0  |   3  | STEMP_2  | K         | T 10-40 cm below ground layer (Upper)   |  2  |  0  |  2  | 106 |
  85 | 112  |   0  |   2  | STEMP_3  | K         | T 40-100 cm below ground layer (Upper)  |  2  |  0  |  2  | 106 |
  85 | 112  |   0  |   1  | STEMP_4  | K         | T 100-200 cm below ground layer (Bottom)|  2  |  0  |  2  | 106 |
geo_em_flnm    = "/data/home/jiangjh/NoahMP/quyu/geo_em.d01.nc"
 flnm = /data/home/jiangjh/NoahMP/quyu/geo_em.d01.nc
 Done with subroutine read_geo_em_file
 Date = 2001-01-02_00  ihour =            0
             :  Checking for file '/data/home/jiangjh/NoahMP/quyu/extracted/Tair/GLDAS_Tair_f_inst_2001010200'
             :  Found file /data/home/jiangjh/NoahMP/quyu/extracted/Tair/GLDAS_Tair_f_inst_2001010200
Returning error from read_grib_unit:  nunit = ***  ierr =   1
 /data/home/jiangjh/NoahMP/quyu/extracted/Tair/GLDAS_Tair_f_inst_2001010200
 Returning error flag from get_single_datastruct_from_grib (1)
 gribunit =              19112640
 flnm = /data/home/jiangjh/NoahMP/quyu/extracted/Tair/GLDAS_Tair_f_inst_2001010200
 ierr =            1

 ********************************************************************************
 *****  
 ***** 
 *****      Requested field name: 'T2D'
 *****      Field name in the Vtable entry:  'ŧ
 ***** 
 *****  Please check your VTable entries and filename templates in your namelist
 *****  to be sure you are getting the fields you think you are getting.
 ********************************************************************************`
It seems like have something wrong when reading the GRIB data, but I can't deal with it. Can you give some help and idea?
Here's the data in extructed
[GLDAS.zip](https://github.com/NCAR/hrldas/files/9128054/GLDAS.zip)

**Comment by CharlesZheZhang** [comment]
Hi Jinghong, 
Please note that the format of the GLDAS data changed from grib to netcdf two years ago. The details of this format change are documented in: https://github.com/NCAR/hrldas/blob/master/hrldas/docs/README.GLDAS

For now, there is a separate code, create_forcing_netcdf.F to deal with this change. Please use create_forcing_netcdf.F for this purpose. 

You can try this:
`cp create_forcing_netcdf.F create_forcing.F`
and compile again. This can deal with the reading netcdf issue. 

This can solve the issue for now and we plan to merge the capabilities for different data formats into one code in the future.

Regards,
Zhe

**Comment by cenlinhe** [comment]
I think this issue was resolved based on Zhe's replies above, so I am closing this issue. Currently, the netcdf reading capability has been merged into the IO code (create_forcing.F).
