### ISSUE TITLE
Hrldas: tutorial step2

### ISSUE THREAD

**Issue by KevinInSomeWhere** [NCAR/hrldas#85]
When i started to ./configure in hrldas, chose 4.Linux ifort compiler MPI.
and: Please reminder to change the software package path in the generated user_build_options file before compiling!

I also checked the /arch/user_build_options.ifort.mpi and changed the path for each packages like netcdf jasper.
: Please reminder to change the software package path in the generated user_build_options file before compiling!

**Comment by cenlinhe** [comment]
after you do the ./configure, the user_build_options file will appear under the current directory, and then modify the user_build_options file, then just type "make" to compile and it should be fine.

**Comment by KevinInSomeWhere** [comment]
Thanks for your reply! I have noticed that whatever compiler I choose, it appers.
